services:
  postgres:
    container_name: postgres-sql-wavechat
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: wavechat
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - wavechat-network
    restart: unless-stopped
  keycloak:
    container_name: keycloak-wavechat
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: wavechat
      KC_DB_URL: jdbc:postgresql://postgres:5432/wavechat
      KC_DB_URL_HOST: postgres
      KC_HOSTNAME: localhost
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - wavechat-network
    command:
      - "start-dev"
    depends_on:
      postgres:
        condition: service_healthy
    mem_limit: 1g
volumes:
  postgres:
    driver: local

networks:
  wavechat-network:
    driver: bridge